### PR TITLE
security implement;

### LINKED ISSUE #62: Security implementation
- Create class `SecurityService` in `./src/service/core/security`. Create factory for that class
- SecurityService must implement next functions:
`http_request handle(http_request request)` - must obtain `Authorization` header from http_request and parse its value as JWT, after which checks its validness. Returns same http_request if everything is okay or throws exception (which represents 403 Forbidden status code) otherwise.
`http_request handle(http_request request)` must only process request if its path is in the restricted path set (meaning you can't visit these routes unauthorized)
`void initialize()` - initializes Jwt-cpp with secret key which should generate on server init
`string generate(string subject)` - generates JWT for specified credentials. Subject in our case means user login
- UserController must implement new function
`http_request login(string login, string password)` - checks database if user with specified credentials exists, if so, then generates JWT via `SecurityService::generate` and replies with 200 OK empty body and `Authorization` header with generated JWT

### PR DESCRIPTION
**Pull request by MainMeatBall**
closes #62

### CODE REVIEW

File: src/controller/user_controller.cpp [hunk 1]
```diff
@@ -57,3 +59,13 @@ http_response UserController::deleteUser(http_request request) {
     userService.deleteUser(stol(requestPath(request)[1]));
     return emptyResponse();
 }
+
+http_response UserController::login(http_request request) {
+    getUser(request);
```
Comment (VagrantAI-c) [inline src/controller/user_controller.cpp]: Impossible to login due to crypted password. User must be obtained only via login, then incoming password must be benchmarked against existing cypher

File: src/controller/user_controller.cpp [hunk 2]
```diff
@@ -57,3 +59,13 @@ http_response UserController::deleteUser(http_request request) {
     userService.deleteUser(stol(requestPath(request)[1]));
     return emptyResponse();
 }
+
+http_response UserController::login(http_request request) {
```
Comment (VagrantAI-c) [inline src/controller/user_controller.cpp]: Create `string login(UserModel user)` in UserService that will return JWT or throw error otherwise and move searching user and generating JWT logic into this function

File: src/controller/user_controller.h [hunk 3]
```diff
@@ -37,4 +40,9 @@ class UserController : public Controller {
 
     // Deletes UserModel by specified id
     http_response deleteUser(http_request request);
+    
+    //if user with specified credentials exists in database generates JWT
```
Comment (VagrantAI-c) [inline src/controller/user_controller.h]: Overall style recommendations: comment must start with a whitespace and uppercase letter

File: src/service/core/forbidden.h [hunk 4]
```diff
@@ -0,0 +1,5 @@
+#pragma once
```
Comment (VagrantAI-c) [inline src/service/core/forbidden.h]: Duplicate file, consider to remove

File: src/service/core/security/security.h [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+#include "jwt/jwt_all.h"
+
+using namespace web::http;
+using namespace std;
+
+class SecurityService {
+private:
+    string secret;
+public:
+    http_request handle(http_request request);
```
Comment (VagrantAI-c) [inline src/service/core/security/security.h]: No implementation found of `http_request handle(http_request request)`

File: version_file/UserService.build/Debug/UserService.build/Objects-normal/x86_64/UserService.LinkFileList [hunk 6]
```diff
@@ -0,0 +1,22 @@
+/Users/Meatball/Documents/UserService/version_file/UserService.build/Debug/UserService.build/Objects-normal/x86_64/security_factory.o
```
Comment (VagrantAI-c) [inline version_file/UserService.build/Debug/UserService.build/Objects-normal/x86_64/UserService.LinkFileList]: How did this get into commit? Check staged files before pushing.

File: src/service/core/security/security.cpp [hunk 7]
```diff
@@ -0,0 +1,38 @@
+#include "security.h"
+#include "../http/web_exceptions/forbidden.h"
+
+http_request SecurityService::handle(http_request request) {
```
Comment (VagrantAI-c) [inline src/service/core/security/security.cpp]: No whitelist implementation, provide whitelisted urls that shouldn't be checked for JWT

File: src/service/core/security/security.cpp [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+    if (!request.headers().has(header_names::authorization)) {
+        throw "no authorization header provided";
```
Comment (VagrantAI-c) [inline src/service/core/security/security.cpp]: `throw forbidden;` instead of string

File: src/service/core/security/security.cpp [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+    }
+    http_headers headers = request.headers();
+    string str_token = headers[header_names::authorization];
+    if (str_token.empty())
+        throw "authorization header is empty";
```
Comment (VagrantAI-c) [inline src/service/core/security/security.cpp]: `throw forbidden;` instead of string

File: src/service/core/security/security.cpp [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+    HS256Validator signer(secret);
+    try {
+        jwt_ptr token(JWT::Decode(str_token, &signer));
+        json_str payload(json_dumps(token->payload(), JSON_INDENT(2)));
+        printf("Payload: %s\n", payload.get());
```
Comment (VagrantAI-c) [inline src/service/core/security/security.cpp]: Unnecessary printf, check if token is valid instead

Comment (VagrantAI-c) [inline src/service/core/security/security.cpp]: Since you're going to use UserService in SecurityService, UserService must implement a singleton factory

File: src/controller/security_controller.cpp [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+SecurityController::SecurityController() : JWTService(JWTServiceFactory::getInstance()), userService(UserServiceFactory::getInstance()) {}
+
+std::vector<utility::string_t> SecurityController::requestPath(const http_request& request) {
+    auto relativePath = uri::decode(request.relative_uri().path());
+    return uri::split_path(relativePath);
+}
+
+
+void SecurityController::handle(http_request request) {
+    if (isInWhitelist(request))
```
Comment (VagrantAI-c) [inline src/controller/security_controller.cpp]: Overall style recommendation: wrap if body in curly braces everytime

File: src/controller/security_controller.cpp [hunk 12]
```diff
@@ -0,0 +1,51 @@
...
+        return;
+    if (!request.headers().has(header_names::authorization)) {
+        throw forbidden;
+    }
+    http_headers headers = request.headers();
+    string str_token = headers[header_names::authorization];
+    if (str_token.empty())
```
Comment (VagrantAI-c) [inline src/controller/security_controller.cpp]: Overall style recommendation: wrap if body in curly braces everytime
